realm reducer [nfc]: Cut some unnecessary concerns in a comment.
Empirically these aren't true.  To see that:

 * Delete this "fake blank state" hack.

 * Try logging into a new account.  (E.g., log out and then log in
   again.)  Observe the red-screen error:

     Error: Error: Error: No server data found

     This error is located at:
         in Connect(UnreadCards) (at HomeTab.js:66)
         in RCTView (at View.js:45)
         in View (at HomeTab.js:37)
         in HomeTab (created by Connect(HomeTab))
         [...]

   Inspecting the code that throws that error, it's caused by
   `state.realm.email` being undefined.

 * Now instead try switching between accounts, or logging out of an
   account.  Observe that it works fine with no error.

We're about to fix the remaining, LOGIN_SUCCESS issue too -- so
that means we'll get to remove this hack entirely.